title: Kit de Campagne Numérique pour Insoumis·e

# Build settings
permalink: /:title/
markdown: kramdown
collections:
  cat_franceinsoumise:
    output: true
    permalink: franceinsoumise/:name/
    title: La France Insoumise
  cat_reseauxsociaux:
    output: true
    permalink: reseauxsociaux/:name/
    title: Réseaux sociaux
  cat_legislatives2017:
    output: true
    permalink: legislatives2017/:name/
    title: Législatives 2017
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - cibuild.sh

gems:
  - jekyll-sitemap
  - jekyll-relative-links
